{% set name = "hypercoast" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypercoast-{{ version }}.tar.gz
  sha256: 9296093da8173849ae0899907ef4ba0c737631d2f31b9c4c2bd3cc444a9d1947

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hypercoast = hypercoast.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - geopandas
    - h5netcdf
    - hvplot
    - leafmap
    - localtileserver
    - netcdf4
    - numpy
    - rioxarray
    - s3fs
    - scipy
    - xarray

test:
  imports:
    - hypercoast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hypercoast.org
  summary: A Python package for visualizing and analyzing hyperspectral data in coastal regions
  license: MIT
  license_file: LICENSE
  doc_url: https://hypercoast.org
  dev_url: https://github.com/opengeos/HyperCoast
  description: A Python package for visualizing and analyzing hyperspectral data in coastal regions

extra:
  recipe-maintainers:
    - bingqing-liu
    - giswqs
