{% set name = "hypercoast" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hypercoast-{{ version }}.tar.gz
  sha256: 2719438594c7d5d11d05739f927d2b55e2cf6a46b1d291461ced589edc0940d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hypercoast = hypercoast.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - dask
    - geopandas
    - h5netcdf
    - hvplot
    - leafmap
    - localtileserver
    - mapclassify
    - netcdf4
    - numpy
    - rioxarray
    - s3fs
    - scipy
    - scikit-learn
    - xarray

test:
  imports:
    - hypercoast
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hypercoast.org
  summary: A Python package for visualizing and analyzing hyperspectral data in coastal regions
  license: MIT
  license_file: LICENSE
  doc_url: https://hypercoast.org
  dev_url: https://github.com/opengeos/HyperCoast
  description: A Python package for visualizing and analyzing hyperspectral data in coastal regions

extra:
  recipe-maintainers:
    - bingqing-liu
    - giswqs
