{% set name = "hypercoast" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypercoast-{{ version }}.tar.gz
  sha256: 2f325f1a4ef781469782a489d90392d8b9727b7dacbe52108aedd06ffbeee1da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hypercoast = hypercoast.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools

  run:
    - python >=3.8
    - dask
    - geopandas
    - h5netcdf
    - hvplot
    - leafmap
    - localtileserver
    - mapclassify
    - netcdf4
    - numpy <2.0.0
    - rioxarray
    - s3fs
    - scipy
    - scikit-learn
    - xarray

test:
  imports:
    - hypercoast
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://hypercoast.org
  summary: A Python package for visualizing and analyzing hyperspectral data in coastal regions
  license: MIT
  license_file: LICENSE
  doc_url: https://hypercoast.org
  dev_url: https://github.com/opengeos/HyperCoast
  description: A Python package for visualizing and analyzing hyperspectral data in coastal regions

extra:
  recipe-maintainers:
    - bingqing-liu
    - giswqs
