{% set name = "hypercoast" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypercoast-{{ version }}.tar.gz
  sha256: e3f12266c9857e6403b3d2f33e096382142513a4d26a7835f1a631cab4c3facc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points: 
    - hypercoast = hypercoast.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - leafmap
    - numpy

test:
  imports:
    - hypercoast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hypercoast.org
  summary: A Python package for visualizing and analyzing hyperspectral data in coastal regions
  license: MIT
  license_file: LICENSE
  doc_url: https://hypercoast.org
  dev_url: https://github.com/opengeos/HyperCoast

extra:
  recipe-maintainers:
    - Bingqing9027
    - giswqs
