{% set name = "hypercoast" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypercoast-{{ version }}.tar.gz
  sha256: b127b2fd6396acc0dc2352cc547283e66327ef310efe98c58e7975c87688afc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hypercoast = hypercoast.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dask
    - geopandas
    - h5netcdf
    - hvplot
    - leafmap
    - localtileserver
    - netcdf4
    - numpy
    - rioxarray
    - s3fs
    - scipy
    - xarray

test:
  imports:
    - hypercoast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hypercoast.org
  summary: A Python package for visualizing and analyzing hyperspectral data in coastal regions
  license: MIT
  license_file: LICENSE
  doc_url: https://hypercoast.org
  dev_url: https://github.com/opengeos/HyperCoast
  description: A Python package for visualizing and analyzing hyperspectral data in coastal regions

extra:
  recipe-maintainers:
    - bingqing-liu
    - giswqs
